# == NORWEGIAN (BOKMÅL) ==

# General strings
[Languages.nb]
  languageCode  = "nb"
  languageName  = "Norsk (bokmål)"
  description   = "Public Money, Public Code - En kampanje for å frigjøre offentlig finansiert programvare som fri programvare"
  fsdefinition  = "Fri programvare gir alle rett til å bruke, studere, dele og forbedre programvare. Denne retten bidrar til å støtte andre grunnleggende friheter som ytringsfrihet, pressefrihet og retten til privatliv."


# Navigation
[Languages.nb.navigation]
[Languages.nb.navigation.links]
  start     = "Start"
  about     = "Om"
  arguments = "Argumenter"
  action    = "Støtt oppropet"
  spread    = "Spre ordet"


# Start banner
[Languages.nb.start]
  subtitle1   = "Hvorfor blir ikke programvare skapt med skattebetalernes penger utgitt som fri programvare?"
  subtitle2   = "Vi ønsker en lovgivning som krever at offentlig finansiert programvare utviklet for offentlig sektor gjøres tilgjengelig for offentligheten under en [fri programvarelisens](https://fsfe.org/freesoftware/basics/summary.html 'Fri programvare gir alle rett til å bruke, studere, dele og forbedre programvare. Denne retten bidrar til å støtte andre grunnleggende friheter som ytringsfrihet, pressefrihet og retten til privatliv.'). Om det er offentlige penger, bør det også være offentlig kode."
  subtitle3   = "**Kode som er betalt av folket bør være tilgjengelig for folket!**" 


# About section
[Languages.nb.about]
  headline    = "Høres komplisert ut? Det er det ikke. Det er veldig enkelt!"
  buttonText  = "Flere fordeler"


# Arguments section
[Languages.nb.arguments]
  headline    = "Argumenter for offentlig kode"
  followup    = "Synes du at fri programvare bør være standardvalget for offentlig finansiert programvare? **La oss overbevise dine politiske representanter!**"
  buttonText  = "Signer det åpne brevet"
[[Languages.nb.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Skattebesparelser"
  description = "Lignende programmer behøver ikke å bli programmert fra start hver gang."
[[Languages.nb.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Samarbeid"
  description = "Innsatsen på større prosjekter kan dele kompetanse og kostnader."  
[[Languages.nb.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Tjener offentligheten"
  description = "Programvare betalt av offentligheten bør være tilgjengelig for alle."
[[Languages.nb.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Fremmer innovasjon"
  description = "Med transparente prosesser, behøver ikke andre å gjenoppfinne hjulet."


# Action section
[Languages.nb.action]
  headline      = "Send budskapet til politikerne!"
  intro         = "I vårt [**åpne brev**](openletter/) ber vi om at det:" 
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Implementeres lovgivning som krever at offentlig finansiert programvare utviklet for offentlig sektor gjøres tilgjengelig for offentligheten under en [fri programvarelisens](https://fsfe.org/freesoftware/basics/summary.html 'Fri programvare gir alle rett til å bruke, studere, dele og forbedre programvare. Denne retten bidrar til å støtte andre grunnleggende friheter som ytringsfrihet, pressefrihet og retten til privatliv.').”"
  description   = "**$ORGS** organisasjoner og **$INDS** individer har allerede støttet oppropet ved å signere vårt [åpne brev](openletter/). Du kan hjelpe oss med å øke slagkraften ved å skrive under du også! Vi vil overlevere alle underskriftene til representanter over hele Europa som diskuterer programvarefrihet i det offentlige."

[Languages.nb.action.box]
  text      = "Alt **$INDS UNDERSKRIFTER** – skriv under på det åpne brevet!"

[Languages.nb.action.form]
  name      = "Navn (nødvendig)"
  email     = "Epost (nødvendig)"
  country   = "Land"
  zip       = "Postnummer"
  comment   = "Din kommentar (maks. 140 tegn)"
  permPriv  = "Jeg har lest og forstått [personvernerklæringen](privacy/)"
  permNews  = "Jeg ønsker å bli informert om kampanjens utvikling"
  permPub   = "Jeg vil at min underskrift vises i [listen over underskrifter](openletter/all-signatures)"
  submit    = "Skriv under!"


# Organisations section
[Languages.nb.organisations]
  headline  = "Støttende organisasjoner"
  text      = "Følgende organisasjoner støtter vårt [åpne brev](openletter/). Om din organisasjon også er interessert i å slutte seg til oppropet for offentlig kode, vennligst [ta kontakt](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.nb.spread]
  headline          = "Spre ordet!"
  promoText         = "Bestill de nyeste klistremerkene og flygebladene fra FSFE"
  promoButtonText   = "Skaff promomateriale"
  shareText         = "Fortell dine venner og følgere om offentlig kode:"
  defaultSocialText = "Om det er offentlige penger, bør det også være offentlig kode. Jeg støtter oppropet for mer offentlig kode under en fri programvarelisens:"


# Legal Section
[Languages.nb.legal]
  by            = "Dette er en kampanje av Free Software Foundation Europe"
  imprint       = "Kolofon"
  privacy       = "Personvern"
  transparency  = "Åpenhet"
  contribute1   = "Koden på dette nettstedet er fri programvare." 
  contribute2   = "Du er velkommen til å bidra!"
  license       = "Dette arbeidet er utgitt under en [Creative Commons BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.no) lisens."


# Language selection
[Languages.nb.language]
  description = "Les denne siden på et annet språk"


# 404 Error Page
[Languages.nb.error]
  headline    = "Error 404 - Side ikke funnet"
  description = "Siden du leter etter eksisterer ikke."
  button      = "Tilbake til startsiden"


# Specific sub-pages
[Languages.nb.subpage]
[Languages.nb.subpage.signatures]
  headline      = "Individuelle underskrifter for det åpne brevet"
  description   = "Under finner du underskriften til alle de som samtykket til å få navnet sitt publisert. Vær den neste!"
  allSignatures = "Vis [alle offentlige underskrifter](all-signatures/)."
  tableName     = "Navn"
  tableCountry  = "Land"
  tableComment  = "Kommentar"

